# Use postgres/example user/password credentials
version: '3.1'

services:

  dev-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: namthanh99
      POSTGRES_DB: nest
    networks:
      - namnt
networks:
  namnt: